// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: foodController.proto

package foodController

import (
	context "context"
	common "food/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userid  string         `protobuf:"bytes,1,opt,name=userid,proto3" json:"userid,omitempty"`
	Cuisine common.Cuisine `protobuf:"varint,2,opt,name=cuisine,proto3,enum=common.Cuisine" json:"cuisine,omitempty"`
}

func (x *FoodRequest) Reset() {
	*x = FoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foodController_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodRequest) ProtoMessage() {}

func (x *FoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foodController_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodRequest.ProtoReflect.Descriptor instead.
func (*FoodRequest) Descriptor() ([]byte, []int) {
	return file_foodController_proto_rawDescGZIP(), []int{0}
}

func (x *FoodRequest) GetUserid() string {
	if x != nil {
		return x.Userid
	}
	return ""
}

func (x *FoodRequest) GetCuisine() common.Cuisine {
	if x != nil {
		return x.Cuisine
	}
	return common.Cuisine(0)
}

type FoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *common.Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *FoodResponse) Reset() {
	*x = FoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foodController_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodResponse) ProtoMessage() {}

func (x *FoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foodController_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodResponse.ProtoReflect.Descriptor instead.
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return file_foodController_proto_rawDescGZIP(), []int{1}
}

func (x *FoodResponse) GetFood() *common.Food {
	if x != nil {
		return x.Food
	}
	return nil
}

var File_foodController_proto protoreflect.FileDescriptor

var file_foodController_proto_rawDesc = []byte{
	0x0a, 0x14, 0x66, 0x6f, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x66, 0x6f, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x0b, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x69, 0x64, 0x12, 0x29, 0x0a, 0x07, 0x63,
	0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x63,
	0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x22, 0x30, 0x0a, 0x0c, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x6f,
	0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x32, 0x5f, 0x0a, 0x15, 0x46, 0x6f, 0x6f, 0x64,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x46, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x12, 0x1b, 0x2e, 0x66,
	0x6f, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x46, 0x6f,
	0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6f, 0x6f, 0x64,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x42, 0x0a, 0x18, 0x63, 0x6f, 0x6d,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x13, 0x66, 0x6f, 0x6f, 0x64, 0x2f, 0x66, 0x6f,
	0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0xaa, 0x02, 0x0e, 0x46,
	0x6f, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foodController_proto_rawDescOnce sync.Once
	file_foodController_proto_rawDescData = file_foodController_proto_rawDesc
)

func file_foodController_proto_rawDescGZIP() []byte {
	file_foodController_proto_rawDescOnce.Do(func() {
		file_foodController_proto_rawDescData = protoimpl.X.CompressGZIP(file_foodController_proto_rawDescData)
	})
	return file_foodController_proto_rawDescData
}

var file_foodController_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foodController_proto_goTypes = []interface{}{
	(*FoodRequest)(nil),  // 0: foodController.FoodRequest
	(*FoodResponse)(nil), // 1: foodController.FoodResponse
	(common.Cuisine)(0),  // 2: common.Cuisine
	(*common.Food)(nil),  // 3: common.Food
}
var file_foodController_proto_depIdxs = []int32{
	2, // 0: foodController.FoodRequest.cuisine:type_name -> common.Cuisine
	3, // 1: foodController.FoodResponse.food:type_name -> common.Food
	0, // 2: foodController.FoodControllerService.getFood:input_type -> foodController.FoodRequest
	1, // 3: foodController.FoodControllerService.getFood:output_type -> foodController.FoodResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_foodController_proto_init() }
func file_foodController_proto_init() {
	if File_foodController_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foodController_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foodController_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foodController_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foodController_proto_goTypes,
		DependencyIndexes: file_foodController_proto_depIdxs,
		MessageInfos:      file_foodController_proto_msgTypes,
	}.Build()
	File_foodController_proto = out.File
	file_foodController_proto_rawDesc = nil
	file_foodController_proto_goTypes = nil
	file_foodController_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FoodControllerServiceClient is the client API for FoodControllerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FoodControllerServiceClient interface {
	// unary rpc call to retrieve a movie
	GetFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error)
}

type foodControllerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodControllerServiceClient(cc grpc.ClientConnInterface) FoodControllerServiceClient {
	return &foodControllerServiceClient{cc}
}

func (c *foodControllerServiceClient) GetFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error) {
	out := new(FoodResponse)
	err := c.cc.Invoke(ctx, "/foodController.FoodControllerService/getFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FoodControllerServiceServer is the server API for FoodControllerService service.
type FoodControllerServiceServer interface {
	// unary rpc call to retrieve a movie
	GetFood(context.Context, *FoodRequest) (*FoodResponse, error)
}

// UnimplementedFoodControllerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFoodControllerServiceServer struct {
}

func (*UnimplementedFoodControllerServiceServer) GetFood(context.Context, *FoodRequest) (*FoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFood not implemented")
}

func RegisterFoodControllerServiceServer(s *grpc.Server, srv FoodControllerServiceServer) {
	s.RegisterService(&_FoodControllerService_serviceDesc, srv)
}

func _FoodControllerService_GetFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FoodControllerServiceServer).GetFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/foodController.FoodControllerService/GetFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FoodControllerServiceServer).GetFood(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FoodControllerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foodController.FoodControllerService",
	HandlerType: (*FoodControllerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getFood",
			Handler:    _FoodControllerService_GetFood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "foodController.proto",
}
