// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: recommender.proto

package recommender

import (
	context "context"
	common "food/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecommenderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cuisine common.Cuisine `protobuf:"varint,1,opt,name=cuisine,proto3,enum=common.Cuisine" json:"cuisine,omitempty"`
}

func (x *RecommenderRequest) Reset() {
	*x = RecommenderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommender_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommenderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommenderRequest) ProtoMessage() {}

func (x *RecommenderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommenderRequest.ProtoReflect.Descriptor instead.
func (*RecommenderRequest) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{0}
}

func (x *RecommenderRequest) GetCuisine() common.Cuisine {
	if x != nil {
		return x.Cuisine
	}
	return common.Cuisine(0)
}

type RecommenderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *common.Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *RecommenderResponse) Reset() {
	*x = RecommenderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommender_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommenderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommenderResponse) ProtoMessage() {}

func (x *RecommenderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommender_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommenderResponse.ProtoReflect.Descriptor instead.
func (*RecommenderResponse) Descriptor() ([]byte, []int) {
	return file_recommender_proto_rawDescGZIP(), []int{1}
}

func (x *RecommenderResponse) GetFood() *common.Food {
	if x != nil {
		return x.Food
	}
	return nil
}

var File_recommender_proto protoreflect.FileDescriptor

var file_recommender_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f,
	0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43,
	0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x22,
	0x37, 0x0a, 0x13, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20, 0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x6f,
	0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x32, 0x71, 0x0a, 0x12, 0x52, 0x65, 0x63, 0x6f,
	0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5b,
	0x0a, 0x12, 0x67, 0x65, 0x74, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64,
	0x46, 0x6f, 0x6f, 0x64, 0x12, 0x1f, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x65, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x39, 0x0a, 0x15, 0x63,
	0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x50, 0x01, 0x5a, 0x10, 0x66, 0x6f, 0x6f, 0x64, 0x2f, 0x72, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0xaa, 0x02, 0x0b, 0x52, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommender_proto_rawDescOnce sync.Once
	file_recommender_proto_rawDescData = file_recommender_proto_rawDesc
)

func file_recommender_proto_rawDescGZIP() []byte {
	file_recommender_proto_rawDescOnce.Do(func() {
		file_recommender_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommender_proto_rawDescData)
	})
	return file_recommender_proto_rawDescData
}

var file_recommender_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recommender_proto_goTypes = []interface{}{
	(*RecommenderRequest)(nil),  // 0: recommender.RecommenderRequest
	(*RecommenderResponse)(nil), // 1: recommender.RecommenderResponse
	(common.Cuisine)(0),         // 2: common.Cuisine
	(*common.Food)(nil),         // 3: common.Food
}
var file_recommender_proto_depIdxs = []int32{
	2, // 0: recommender.RecommenderRequest.cuisine:type_name -> common.Cuisine
	3, // 1: recommender.RecommenderResponse.food:type_name -> common.Food
	0, // 2: recommender.RecommenderService.getRecommendedFood:input_type -> recommender.RecommenderRequest
	1, // 3: recommender.RecommenderService.getRecommendedFood:output_type -> recommender.RecommenderResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommender_proto_init() }
func file_recommender_proto_init() {
	if File_recommender_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommender_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommenderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommender_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommenderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommender_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommender_proto_goTypes,
		DependencyIndexes: file_recommender_proto_depIdxs,
		MessageInfos:      file_recommender_proto_msgTypes,
	}.Build()
	File_recommender_proto = out.File
	file_recommender_proto_rawDesc = nil
	file_recommender_proto_goTypes = nil
	file_recommender_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RecommenderServiceClient is the client API for RecommenderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecommenderServiceClient interface {
	GetRecommendedFood(ctx context.Context, in *RecommenderRequest, opts ...grpc.CallOption) (RecommenderService_GetRecommendedFoodClient, error)
}

type recommenderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecommenderServiceClient(cc grpc.ClientConnInterface) RecommenderServiceClient {
	return &recommenderServiceClient{cc}
}

func (c *recommenderServiceClient) GetRecommendedFood(ctx context.Context, in *RecommenderRequest, opts ...grpc.CallOption) (RecommenderService_GetRecommendedFoodClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RecommenderService_serviceDesc.Streams[0], "/recommender.RecommenderService/getRecommendedFood", opts...)
	if err != nil {
		return nil, err
	}
	x := &recommenderServiceGetRecommendedFoodClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RecommenderService_GetRecommendedFoodClient interface {
	Recv() (*RecommenderResponse, error)
	grpc.ClientStream
}

type recommenderServiceGetRecommendedFoodClient struct {
	grpc.ClientStream
}

func (x *recommenderServiceGetRecommendedFoodClient) Recv() (*RecommenderResponse, error) {
	m := new(RecommenderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RecommenderServiceServer is the server API for RecommenderService service.
type RecommenderServiceServer interface {
	GetRecommendedFood(*RecommenderRequest, RecommenderService_GetRecommendedFoodServer) error
}

// UnimplementedRecommenderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRecommenderServiceServer struct {
}

func (*UnimplementedRecommenderServiceServer) GetRecommendedFood(*RecommenderRequest, RecommenderService_GetRecommendedFoodServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRecommendedFood not implemented")
}

func RegisterRecommenderServiceServer(s *grpc.Server, srv RecommenderServiceServer) {
	s.RegisterService(&_RecommenderService_serviceDesc, srv)
}

func _RecommenderService_GetRecommendedFood_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecommenderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RecommenderServiceServer).GetRecommendedFood(m, &recommenderServiceGetRecommendedFoodServer{stream})
}

type RecommenderService_GetRecommendedFoodServer interface {
	Send(*RecommenderResponse) error
	grpc.ServerStream
}

type recommenderServiceGetRecommendedFoodServer struct {
	grpc.ServerStream
}

func (x *recommenderServiceGetRecommendedFoodServer) Send(m *RecommenderResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RecommenderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "recommender.RecommenderService",
	HandlerType: (*RecommenderServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getRecommendedFood",
			Handler:       _RecommenderService_GetRecommendedFood_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "recommender.proto",
}
