// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: foodStore.proto

package foodStore

import (
	context "context"
	common "food/common"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FoodStoreRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cuisine common.Cuisine `protobuf:"varint,1,opt,name=cuisine,proto3,enum=common.Cuisine" json:"cuisine,omitempty"`
}

func (x *FoodStoreRequest) Reset() {
	*x = FoodStoreRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foodStore_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodStoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStoreRequest) ProtoMessage() {}

func (x *FoodStoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_foodStore_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStoreRequest.ProtoReflect.Descriptor instead.
func (*FoodStoreRequest) Descriptor() ([]byte, []int) {
	return file_foodStore_proto_rawDescGZIP(), []int{0}
}

func (x *FoodStoreRequest) GetCuisine() common.Cuisine {
	if x != nil {
		return x.Cuisine
	}
	return common.Cuisine(0)
}

type FoodStoreResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Food *common.Food `protobuf:"bytes,1,opt,name=food,proto3" json:"food,omitempty"`
}

func (x *FoodStoreResponse) Reset() {
	*x = FoodStoreResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_foodStore_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FoodStoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FoodStoreResponse) ProtoMessage() {}

func (x *FoodStoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_foodStore_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FoodStoreResponse.ProtoReflect.Descriptor instead.
func (*FoodStoreResponse) Descriptor() ([]byte, []int) {
	return file_foodStore_proto_rawDescGZIP(), []int{1}
}

func (x *FoodStoreResponse) GetFood() *common.Food {
	if x != nil {
		return x.Food
	}
	return nil
}

var File_foodStore_proto protoreflect.FileDescriptor

var file_foodStore_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x10, 0x46, 0x6f,
	0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29,
	0x0a, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x0f, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65,
	0x52, 0x07, 0x63, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x22, 0x35, 0x0a, 0x11, 0x46, 0x6f, 0x6f,
	0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x04, 0x66, 0x6f, 0x6f, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x52, 0x04, 0x66, 0x6f, 0x6f, 0x64,
	0x32, 0x61, 0x0a, 0x10, 0x46, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x4d, 0x0a, 0x0c, 0x67, 0x65, 0x74, 0x46, 0x6f, 0x6f, 0x64, 0x53,
	0x74, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x46, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x46, 0x6f,
	0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x30, 0x01, 0x42, 0x33, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x50, 0x01, 0x5a, 0x0e, 0x66, 0x6f,
	0x6f, 0x64, 0x2f, 0x66, 0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0xaa, 0x02, 0x09, 0x46,
	0x6f, 0x6f, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_foodStore_proto_rawDescOnce sync.Once
	file_foodStore_proto_rawDescData = file_foodStore_proto_rawDesc
)

func file_foodStore_proto_rawDescGZIP() []byte {
	file_foodStore_proto_rawDescOnce.Do(func() {
		file_foodStore_proto_rawDescData = protoimpl.X.CompressGZIP(file_foodStore_proto_rawDescData)
	})
	return file_foodStore_proto_rawDescData
}

var file_foodStore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_foodStore_proto_goTypes = []interface{}{
	(*FoodStoreRequest)(nil),  // 0: foodStore.FoodStoreRequest
	(*FoodStoreResponse)(nil), // 1: foodStore.FoodStoreResponse
	(common.Cuisine)(0),       // 2: common.Cuisine
	(*common.Food)(nil),       // 3: common.Food
}
var file_foodStore_proto_depIdxs = []int32{
	2, // 0: foodStore.FoodStoreRequest.cuisine:type_name -> common.Cuisine
	3, // 1: foodStore.FoodStoreResponse.food:type_name -> common.Food
	0, // 2: foodStore.FoodStoreService.getFoodStore:input_type -> foodStore.FoodStoreRequest
	1, // 3: foodStore.FoodStoreService.getFoodStore:output_type -> foodStore.FoodStoreResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_foodStore_proto_init() }
func file_foodStore_proto_init() {
	if File_foodStore_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_foodStore_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodStoreRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_foodStore_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FoodStoreResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_foodStore_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_foodStore_proto_goTypes,
		DependencyIndexes: file_foodStore_proto_depIdxs,
		MessageInfos:      file_foodStore_proto_msgTypes,
	}.Build()
	File_foodStore_proto = out.File
	file_foodStore_proto_rawDesc = nil
	file_foodStore_proto_goTypes = nil
	file_foodStore_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// FoodStoreServiceClient is the client API for FoodStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FoodStoreServiceClient interface {
	GetFoodStore(ctx context.Context, in *FoodStoreRequest, opts ...grpc.CallOption) (FoodStoreService_GetFoodStoreClient, error)
}

type foodStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFoodStoreServiceClient(cc grpc.ClientConnInterface) FoodStoreServiceClient {
	return &foodStoreServiceClient{cc}
}

func (c *foodStoreServiceClient) GetFoodStore(ctx context.Context, in *FoodStoreRequest, opts ...grpc.CallOption) (FoodStoreService_GetFoodStoreClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FoodStoreService_serviceDesc.Streams[0], "/foodStore.FoodStoreService/getFoodStore", opts...)
	if err != nil {
		return nil, err
	}
	x := &foodStoreServiceGetFoodStoreClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FoodStoreService_GetFoodStoreClient interface {
	Recv() (*FoodStoreResponse, error)
	grpc.ClientStream
}

type foodStoreServiceGetFoodStoreClient struct {
	grpc.ClientStream
}

func (x *foodStoreServiceGetFoodStoreClient) Recv() (*FoodStoreResponse, error) {
	m := new(FoodStoreResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FoodStoreServiceServer is the server API for FoodStoreService service.
type FoodStoreServiceServer interface {
	GetFoodStore(*FoodStoreRequest, FoodStoreService_GetFoodStoreServer) error
}

// UnimplementedFoodStoreServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFoodStoreServiceServer struct {
}

func (*UnimplementedFoodStoreServiceServer) GetFoodStore(*FoodStoreRequest, FoodStoreService_GetFoodStoreServer) error {
	return status.Errorf(codes.Unimplemented, "method GetFoodStore not implemented")
}

func RegisterFoodStoreServiceServer(s *grpc.Server, srv FoodStoreServiceServer) {
	s.RegisterService(&_FoodStoreService_serviceDesc, srv)
}

func _FoodStoreService_GetFoodStore_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FoodStoreRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FoodStoreServiceServer).GetFoodStore(m, &foodStoreServiceGetFoodStoreServer{stream})
}

type FoodStoreService_GetFoodStoreServer interface {
	Send(*FoodStoreResponse) error
	grpc.ServerStream
}

type foodStoreServiceGetFoodStoreServer struct {
	grpc.ServerStream
}

func (x *foodStoreServiceGetFoodStoreServer) Send(m *FoodStoreResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _FoodStoreService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "foodStore.FoodStoreService",
	HandlerType: (*FoodStoreServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "getFoodStore",
			Handler:       _FoodStoreService_GetFoodStore_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "foodStore.proto",
}
